# Generated by Django 3.1.2 on 2020-10-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201020_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='finished',
            field=models.DateField(blank=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='score',
            field=models.IntegerField(blank=True, verbose_name='Score'),
        ),
    ]
