# Generated by Django 3.1.2 on 2020-10-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201020_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='finished',
            field=models.DateField(blank=True, null=True, verbose_name='Finished'),
        ),
    ]
