# Generated by Django 3.1.2 on 2020-10-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201024_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.FloatField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
