# Generated by Django 3.1.2 on 2020-10-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.FloatField(null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='game',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.series'),
        ),
    ]
