# Generated by Django 3.1.2 on 2020-10-31 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20201026_1223'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('developer', 'name')},
        ),
    ]
