# Generated by Django 3.1.2 on 2020-11-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20201031_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.URLField(blank=True, null=True, verbose_name='Image url'),
        ),
    ]
